In [0]:
#Абдыкалыкова Асель

In [0]:
import torch
from torch.autograd import Variable
import numpy as np
import torch.functional as F
import torch.nn.functional as F
from scipy import sparse

In [25]:
text_1 = ['It is Python code to implement glove but it is not finished yet because code is just only until the cooccurence part']

#Function dividing text into words
def tokenize(text):
    tokens = [x.lower().split() for x in text]
    return tokens
token_size=len(tokens)
tokens = tokenize(text_1)

#Creating vocabulary with unique words with index
vocabulary = []
for word in tokens:
    for token in word:
        if token not in vocabulary:
            vocabulary.append(token)
word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}
vocabulary_size = len(vocabulary)

print(tokens)
print(word2idx)
print(idx2word)

[['it', 'is', 'python', 'code', 'to', 'implement', 'glove', 'but', 'it', 'is', 'not', 'finished', 'yet', 'because', 'code', 'is', 'just', 'only', 'until', 'the', 'cooccurence', 'part']]
{'it': 0, 'is': 1, 'python': 2, 'code': 3, 'to': 4, 'implement': 5, 'glove': 6, 'but': 7, 'not': 8, 'finished': 9, 'yet': 10, 'because': 11, 'just': 12, 'only': 13, 'until': 14, 'the': 15, 'cooccurence': 16, 'part': 17}
{0: 'it', 1: 'is', 2: 'python', 3: 'code', 4: 'to', 5: 'implement', 6: 'glove', 7: 'but', 8: 'not', 9: 'finished', 10: 'yet', 11: 'because', 12: 'just', 13: 'only', 14: 'until', 15: 'the', 16: 'cooccurence', 17: 'part'}


In [24]:
cooccurence=np.zeros((vocabulary_size,vocabulary_size))
token = tokens[0]
for idx in range (len(token)-1):
    ind1 = word2idx[token[idx]]
    ind2 = word2idx[token[idx+1]]
    
    
    cooccurence[ind1,ind2]+=1
print(cooccurence)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.